version: '2'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: menu_db
    volumes:
      - ./src/main/resources/db/migration/V1__23012024.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/db
    ports:
      - "5432:5432"
  authorization-service:
    depends_on:
      - postgres
    container_name: menu-service
    image: menu-service
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/menu_db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      CUSTOMER_SECRET: secret
    ports:
      - "8080:8080"

networks:
  service-network:
    driver: bridge

volumes:
  postgres:
    driver: local