server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate

auth-signing-secret: ${CUSTOMER_SECRET}
access-token-expiration: 2

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /api-docs.yml